version: '2'
services:
  web:
    build: php
    volumes:
      - ./app:/var/www/html/
    ports:
      - 80:80
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
    ports:
      - 8080:80